spring:
# 配置整个单体应用在eureka服务上的名称.
  application:
    name: order
  redis:
    host: localhost
    port: 6379    
# 配置整个连接数据库连接信息.
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: dong
    password: java
# 配置RabbitMQ(已经放置到github config配置中心).
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672  
# 设置spring.data.jpa.show-sql为true,将生成的hql语句打印到控制台上.
  jpa:
    show-sql: true
# 配置ribbon的负载均衡策略(random随机访问,默认为roundrobin轮询发送).
# product:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  test ok
girl:
  name: jerry
  age: 18
