# 配置eureka服务端的注册地址url
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    # 向eureka注册中心注册组件服务(component-service)
    register-with-eureka: true
    # 拉取注册表的本地副本
    fetch-registry: true
  # 使用注册服务的ip地址,而不是基于服务的名称
  instance:
    prefer-ip-address: true
# 配置客户端应用名称
spring:
  application:
    name: eureka-client
  # spring允许后面定义的bean覆盖已经存在的bean定义
  main:
    allow-bean-definition-overridng: true

# 设置eureka客户端服务的port地址为8081
server:
  port: 8081

# 配置服务以指向OAuth2验证服务 {http://localhost:8087/user}
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8087/user