apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: svc
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 180
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 6
          image: registry.cn-shanghai.aliyuncs.com/spotify-music/config-server:latest
          ports:
            - containerPort: 8082