apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: svc
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 60
            failureThreshold: 6
          image: registry.cn-shanghai.aliyuncs.com/spotify-music/api-gateway:latest
          ports:
            - containerPort: 8086