version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    networks:
      - webnet
networks:
  webnet:
