# 修改eureka服务的端口号.
server:
  port: 8762
# 配置eureka服务端的注册地址url.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
# 将eureka服务端不显示在eureka控制面板上.
    register-with-eureka: false
# 关闭springcloud的自我保护模式,在product生产环境不建议关闭.
#  server:
#    enable-self-preservation: false
# 在eureka控制面板中显示的服务名称.
spring:
  application:
    name: eureka