apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: svc
spec:
  selector:
    matchLabels:
      app: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8762
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
          image: registry.cn-hangzhou.aliyuncs.com/spotify-music/eureka-server:latest
          ports:
            - containerPort: 8762