apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: svc
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            timeoutSeconds: 15
            periodSeconds: 60
            failureThreshold: 6
          image: registry.cn-shanghai.aliyuncs.com/spotify-music/user-service:latest
          ports:
            - containerPort: 8084