# 修改eureka服务的端口号.
server:
  port: 8762
# 配置eureka服务端的注册地址url
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    # 应用本身为注册中心服务,不需要注册其本身
    register-with-eureka: false
    # 应用不在本地缓存注册表相关信息
    fetch-registry: false
  # 关闭spring-cloud的自我保护模式,在product生产环境不建议关闭.
  server:
    enable-self-preservation: false
    # 在服务器接收请求之前等待的初始时间(在本地环境可以注释该配置,用于快速发现注册的应用)
  instance:
    hostname: eureka-server.svc
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#    wait-time-in-ms-when-sync-empty: 5
# 在eureka控制面板中显示的服务名称
spring:
  application:
    name: eureka-server

# exposed /actuator/health path for kubernetes liveness probe
management:
  endpoints:
    web:
      exposure:
        include: '*'