spring:
  application:
    name: oauth2-service
  # 目前应用运行指定profile为jwt-config-profile
  profiles:
    active: jwt-config-profile

server:
  port: 8087

# 配置java-web-token签名秘钥
jwt:
  signing-key: "345345fsdgsf5345"

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.101:8762/eureka/
